name: ci

on:
  push:
    branches:
      - main
      - feat/quotes-scrapper
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and run via Make
        run: make ci
